import { UserRole } from "../types";

export interface MockDocument {
  id: string;
  code: string;
  title: string;
  frequency: string;
  officerResponsible: string;
  type: 'needs' | 'budget';
  status: 'pending' | 'approved' | 'rejected';
  authorId: string;
  authorRole: UserRole;
  assignedTo: "Secretary" | "Treasurer" | "Both";
  createdAt: any;
  updatedAt: any;
  budgetAmount?: number;
  barangayName?: string;
}

export const MOCK_DOCUMENTS: MockDocument[] = [
  {
    id: 'doc-cbydp',
    code: 'CBYDP',
    title: 'Comprehensive Barangay Youth Development Plan (CBYDP)',
    frequency: '3-year rolling plan',
    officerResponsible: 'SK Council with KK / SK Secretary',
    type: 'needs',
    status: 'approved',
    authorId: 'sec-1',
    authorRole: 'Secretary',
    assignedTo: 'Secretary',
    createdAt: new Date('2026-05-10'),
    updatedAt: new Date('2026-05-12'),
  },
  {
    id: 'doc-abyip',
    code: 'ABYIP',
    title: 'Annual Barangay Youth Investment Program (ABYIP)',
    frequency: 'Yearly',
    officerResponsible: 'SK Secretary / SK Treasurer',
    type: 'needs',
    status: 'approved',
    authorId: 'sec-1',
    authorRole: 'Secretary',
    assignedTo: 'Both',
    createdAt: new Date('2026-05-12'),
    updatedAt: new Date('2026-05-13'),
  },
  {
    id: 'doc-annual-budget',
    code: 'ANNUAL-BUDGET',
    title: 'SK Annual Budget',
    frequency: 'Yearly',
    officerResponsible: 'SK Secretary / SK Treasurer',
    type: 'budget',
    status: 'approved',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Both',
    createdAt: new Date('2026-05-14'),
    updatedAt: new Date('2026-05-15'),
    budgetAmount: 1450000,
  },
  {
    id: 'doc-accomp',
    code: 'ACCOMP-REP',
    title: 'Accomplishment Report',
    frequency: 'Yearly',
    officerResponsible: 'SK Secretary',
    type: 'needs',
    status: 'pending',
    authorId: 'sec-1',
    authorRole: 'Secretary',
    assignedTo: 'Secretary',
    createdAt: new Date('2026-05-16'),
    updatedAt: new Date('2026-05-16'),
  },
  {
    id: 'doc-annual-liq',
    code: 'ANNUAL-LIQ',
    title: 'Annual Liquidation Report',
    frequency: 'Yearly',
    officerResponsible: 'SK Treasurer',
    type: 'budget',
    status: 'pending',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-17'),
    updatedAt: new Date('2026-05-17'),
    budgetAmount: 1380000,
  },
  {
    id: 'doc-scbaa',
    code: 'SCBAA',
    title: 'Statement of Comparison of Budget and Actual Amounts',
    frequency: 'Yearly',
    officerResponsible: 'SK Budget Monitoring Officer',
    type: 'budget',
    status: 'pending',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-18'),
    updatedAt: new Date('2026-05-18'),
  },
  {
    id: 'doc-inv-equip',
    code: 'RIPPE',
    title: 'Inventory of Purchased Property and Equipment',
    frequency: 'Yearly',
    officerResponsible: 'SK Inventory Head / Treasurer',
    type: 'budget',
    status: 'approved',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-18'),
    updatedAt: new Date('2026-05-19'),
  },
  {
    id: 'doc-notes-fs',
    code: 'NOTES-FS',
    title: 'Notes to Financial Statements',
    frequency: 'Yearly',
    officerResponsible: 'SK Treasurer',
    type: 'budget',
    status: 'pending',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-19'),
    updatedAt: new Date('2026-05-19'),
  },
  {
    id: 'doc-inv-supplies',
    code: 'RIPSM',
    title: 'Inventory of Purchased Supplies and Materials',
    frequency: 'Every 6 months',
    officerResponsible: 'SK Inventory Head / Treasurer',
    type: 'budget',
    status: 'approved',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-20'),
    updatedAt: new Date('2026-05-20'),
  },
  {
    id: 'doc-rbcpb',
    code: 'RBCPB',
    title: 'Registry of Budget, Commitments, Payments and Balances',
    frequency: 'Every 3 months',
    officerResponsible: 'SK Budget Monitoring Officer',
    type: 'budget',
    status: 'pending',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-21'),
    updatedAt: new Date('2026-05-21'),
  },
  {
    id: 'doc-rcrdot',
    code: 'RCRDOT',
    title: 'Register of Cash Receipts, Deposits and Other Transactions',
    frequency: 'Every 3 months',
    officerResponsible: 'SK Treasurer',
    type: 'budget',
    status: 'approved',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-22'),
    updatedAt: new Date('2026-05-22'),
  },
  {
    id: 'doc-rcib',
    code: 'RCIB',
    title: 'Registry of Cash in Bank',
    frequency: 'Every 3 months',
    officerResponsible: 'SK Treasurer',
    type: 'budget',
    status: 'approved',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-22'),
    updatedAt: new Date('2026-05-23'),
  },
  {
    id: 'doc-raaf',
    code: 'RAAF',
    title: 'Report of Accountability for Accountable Forms',
    frequency: 'Every 3 months',
    officerResponsible: 'SK Treasurer',
    type: 'budget',
    status: 'approved',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-23'),
    updatedAt: new Date('2026-05-23'),
  },
  {
    id: 'doc-sbcpb',
    code: 'SBCPB',
    title: 'Summary of Budget, Commitments, Payments and Balances',
    frequency: 'Every 3 months',
    officerResponsible: 'SK Budget Monitoring Officer',
    type: 'budget',
    status: 'pending',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-24'),
    updatedAt: new Date('2026-05-24'),
  },
  {
    id: 'doc-srp',
    code: 'SRP',
    title: 'Statement of Receipts and Payments',
    frequency: 'Every 3 months and yearly',
    officerResponsible: 'SK Treasurer',
    type: 'budget',
    status: 'approved',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-25'),
    updatedAt: new Date('2026-05-25'),
  },
  {
    id: 'doc-brs',
    code: 'BRS',
    title: 'Bank Reconciliation Statement (BRS)',
    frequency: 'Every month',
    officerResponsible: 'SK Treasurer',
    type: 'budget',
    status: 'approved',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-26'),
    updatedAt: new Date('2026-05-26'),
  },
  {
    id: 'doc-dv',
    code: 'DV',
    title: 'Disbursement Voucher (DV)',
    frequency: 'Every transaction',
    officerResponsible: 'SK BMO / SK Treasurer',
    type: 'budget',
    status: 'approved',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-27'),
    updatedAt: new Date('2026-05-27'),
    budgetAmount: 48500,
  },
  {
    id: 'doc-liq-tx',
    code: 'LIQ-REP',
    title: 'Liquidation Report',
    frequency: 'Every transaction',
    officerResponsible: 'SK Treasurer',
    type: 'budget',
    status: 'pending',
    authorId: 'trea-1',
    authorRole: 'Treasurer',
    assignedTo: 'Treasurer',
    createdAt: new Date('2026-05-28'),
    updatedAt: new Date('2026-05-28'),
    budgetAmount: 25000,
  }
];
